#!/usr/bin/env python

Import("env")

harmonyos_files = [
    "os_harmonyos.cpp",
    "harmonyos_main.cpp",
    "harmonyos_dbg.cpp",
    "dir_access_harmonyos.cpp",
    "file_access_harmonyos.cpp",
    "display_server_harmonyos.cpp",
    "harmonyos_native_window.cpp",
    "harmonyos_input.cpp",
    "harmonyos_audio.cpp",
    "audio_driver_ohos.cpp",
    "joypad_harmonyos.cpp",
    "crash_handler_harmonyos.cpp",
    "tts_harmonyos.cpp",
    "rendering_context_driver_vulkan_harmonyos.cpp",
]

if env.editor_build:
    harmonyos_files += [
        "export/export.cpp",
        "export/export_plugin.cpp",
    ]

env_harmonyos = env.Clone()

harmonyos_objects = []
for x in harmonyos_files:
    harmonyos_objects.append(env_harmonyos.SharedObject(x))

lib = env_harmonyos.add_shared_library("#bin/libgodot", harmonyos_objects, redirect_build_objects=False)
